# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Susan Pan
email: susanjsp@protonmail.com
author: Susan Pan
timezone: Australia/Brisbane # see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
description: >- # this means to ignore newlines until "baseurl:"
  I created this blog to document my career journey from Pharmacist to Software Engineering.
  I hope to solidify my learning and to also develop my written communication skills through writing technical posts about web development.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter: "http://www.twitter.com/susanjsp_"
github:  "http://github.com/susanjsp"
codepen: "https://codepen.io/susanjsp"
linkedin: "https://www.linkedin.com/in/susanpan96/"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Gems
gems:
  - jekyll-fontawesome-svg

# Other
excerpt_separator: <!--break-->